% This test file was generated by Copilot. Validate generated output before use.
classdef TcopytableTestEventtable < matlab.unittest.TestCase
    methods(Test)
        function testBaseEventtable(testCase)
            Time = datetime(2022,11,[3 5 10 14]);
            labels = ["Hail","Rain","Snow","Rain"];
            lengths = hours([1.2 36 18 20]);
            ET = eventtable(Time,EventLabels=labels,EventLengths=lengths);

            copytable(ET)
            actual = clipboard('paste');
            actualDouble = double(actual);
            expectedDouble = [84, 105, 109, 101, 44, 69, 118, 101, 110, 116, 76,...
                97, 98, 101, 108, 115, 44, 69, 118, 101, 110, 116, 76, 101,...
                110, 103, 116, 104, 115, 10, 48, 51, 45, 78, 111, 118, 45, 50,...
                48, 50, 50, 44, 72, 97, 105, 108, 44, 49, 46, 50, 32, 104, 114,...
                10, 48, 53, 45, 78, 111, 118, 45, 50, 48, 50, 50, 44, 82, 97,...
                105, 110, 44, 51, 54, 32, 104, 114, 10, 49, 48, 45, 78, 111,...
                118, 45, 50, 48, 50, 50, 44, 83, 110, 111, 119, 44, 49, 56, 32,...
                104, 114, 10, 49, 52, 45, 78, 111, 118, 45, 50, 48, 50, 50, 44,...
                82, 97, 105, 110, 44, 50, 48, 32, 104, 114];

            testCase.verifyEqual(actualDouble,expectedDouble)
        end

        function testSingleRowEventtable(testCase)
            % single-row eventtable preserves contents after copy
            Time = datetime(2023,1,1,12,0,0);
            labels = "Storm";
            lengths = hours(2.5);
            ET = eventtable(Time,EventLabels=labels,EventLengths=lengths);
            
            copytable(ET)
            actual = clipboard('paste');
            actualDouble = double(actual);
            expectedDouble = [84, 105, 109, 101, 44, 69, 118, 101, 110, 116,...
                76, 97, 98, 101, 108, 115, 44, 69, 118, 101, 110, 116, 76, 101,...
                110, 103, 116, 104, 115, 10, 48, 49, 45, 74, 97, 110, 45, 50,...
                48, 50, 51, 32, 49, 50, 58, 48, 48, 58, 48, 48, 44, 83, 116,...
                111, 114, 109, 44, 50, 46, 53, 32, 104, 114];

            testCase.verifyEqual(actualDouble,expectedDouble)
        end


    end
end