% This is an autogenerated sample test
classdef TcopytableIncludeHeaders < matlab.unittest.TestCase
    methods (Test)
        function testBaseHeaderOff(testCase)
            % Specify the inputs
            LastName = ["Sanchez";"Johnson"];
            Age = {38;[]};
            yy = {single(4);half(3)};
            T = table(LastName, Age, yy);
            delimiter = '\t';
            copytable(T,delimiter,false)

            actual = clipboard('paste');
            actualDouble = double(actual);
            expectedDouble = [83, 97, 110, 99, 104, 101, 122, 9, 51, 56, 9, 52,...
                10, 74, 111, 104, 110, 115, 111, 110, 9, 9, 51];

            testCase.verifyEqual(actualDouble, expectedDouble);
        end

        function testDelimiterAndHeadersOn(testCase)
            % Specify the inputs
            LastName = ["Sanchez";"Johnson"];
            Age = {38;[]};
            yy = {single(4);half(3)};
            T = table(LastName, Age, yy);
            delimiter = '\r';
            copytable(T,delimiter,true)

            actual = clipboard('paste');
            expected = ['LastName',char(13),'Age',char(13),'yy',newline,...
                'Sanchez',char(13),'38',char(13),'4',newline,'Johnson',char(13),char(13),'3'];

            testCase.verifyEqual(actual, expected);
        end

        function testBaseNewlineAndNoHeaders(testCase)
            % Specify the inputs
            LastName = ["Sanchez";"Johnson"];
            Age = {38;[]};
            yy = {single(4);half(3)};
            T = table(LastName, Age, yy);
            delimiter = '\n';
            copytable(T,delimiter,false)

            actual = clipboard('paste');
            expectedLines = ['Sanchez',newline,'38',newline,'4',newline,'Johnson',...
                newline,'',newline,'3'];
            
            testCase.verifyEqual(actual, expectedLines);
        end


    end
end