% This test file was generated by Copilot. Validate generated output before use.
classdef TcopytableTestUITable < matlab.unittest.TestCase
    methods(Test)

        function testCopyFromUitableWithColumnNames(testCase)
            dataCell = {'John', 25, 68.5; 'Sarah', 30, 72.0};
            fig = uifigure;
            uit = uitable(fig,'Data', dataCell, 'ColumnName', {'Name', 'Age', 'Weight'});
            testCase.verifyWarningFree(@() copytable(uit));
            
            expectedLines = {strjoin(string(uit.ColumnName(:)'),','),...
                "John,25,68.5","Sarah,30,72"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)
        end

        function testCopyFromUitableWithTooManyColumnNames(testCase)
            dataCell = {'John', 25, 68.5; 'Sarah', 30, 72.0};
            fig = uifigure;
            uit = uitable(fig,'Data', dataCell, 'ColumnName', {'Name', 'Age', 'Weight','Extra','Unused','Columns'});
            testCase.verifyWarningFree(@() copytable(uit));

            actual = clipboard('paste');
            actualDouble = double(actual);
            expectedDouble = [78, 97, 109, 101, 44, 65, 103, 101, 44, 87, 101,...
                105, 103, 104, 116, 10, 74, 111, 104, 110, 44, 50, 53, 44, 54,...
                56, 46, 53, 10, 83, 97, 114, 97, 104, 44, 51, 48, 44, 55, 50];
           
            testCase.verifyEqual(actualDouble, expectedDouble); 

            delete(fig)
        end

        function testCopyFromUitableWithNotEnoughColumnNames(testCase)
            dataCell = {'John', 25, 68.5; 'Sarah', 30, 72.0};
            fig = uifigure;
            uit = uitable(fig,'Data', dataCell, 'ColumnName', {'Name', 'Age'});
            testCase.verifyWarningFree(@() copytable(uit));

            actual = clipboard('paste');
            actualDouble = double(actual);
            expectedDouble = [78, 97, 109, 101, 44, 65, 103, 101, 44, 86, 97,...
                114, 49, 10, 74, 111, 104, 110, 44, 50, 53, 44, 54, 56, 46, 53,...
                10, 83, 97, 114, 97, 104, 44, 51, 48, 44, 55, 50];

            testCase.verifyEqual(actualDouble, expectedDouble); 

            delete(fig)
        end


        function testGetUITableColumnName_numbered(testCase)
            fig = uifigure;
            d = string(ones(3,3));
            uit = uitable(fig,"Data",d);
            testCase.verifyWarningFree(@() copytable(uit));
            
            expectedLines = {"1,2,3",...
                "1,1,1", "1,1,1", "1,1,1"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)
            
        end

        function testUItableEmptyColumnNames(testCase)
            fig = uifigure;
            d = ones(3,3);
            uit = uitable(fig, "Data", d, "ColumnName", []);

            testCase.verifyWarningFree(@() copytable(uit));
            
            expectedLines = {"1,1,1", "1,1,1", "1,1,1"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)
        end

        function testUItableNumericData(testCase)
            fig = uifigure;
            d = ones(3,3);
            uit = uitable(fig, "Data", d);

            testCase.verifyWarningFree(@() copytable(uit));
            
            expectedLines = {"1,2,3",...
                "1,1,1", "1,1,1", "1,1,1"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)
        end

        function testUITableDatetime(testCase)

            T = table( ...
                datetime(2025,1,1)+days([0;1]), ...
                [10;20], ...
                'VariableNames',{'Time','Value'});

            fig = uifigure;
            uit = uitable(fig,"Data",T);

            testCase.verifyWarningFree(@() copytable(uit));

            expectedLines = {strjoin(string(uit.ColumnName(:)'),','),...
                "01-Jan-2025,10","02-Jan-2025,20"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)
        end

        function testUITableDatetimeNaT(testCase)

            T = table( ...
                [datetime(2025,1,1); NaT], ...
                [10;20], ...
                'VariableNames',{'Time','Value'});

            fig = uifigure;
            uit = uitable(fig,"Data",T);

            testCase.verifyWarningFree(@() copytable(uit));

            expectedLines = {strjoin(string(uit.ColumnName(:)'),','),...
                "01-Jan-2025,10",",20"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)

        end

        function testUITableDuration(testCase)

            T = table( ...
                hours([1.5;2.5]), ...
                [10;20], ...
                'VariableNames',{'Elapsed','Value'});

            fig = uifigure;
            uit = uitable(fig,"Data",T);

            testCase.verifyWarningFree(@() copytable(uit));

            expectedLines = {strjoin(string(uit.ColumnName(:)'),','),...
                "1.5 hr,10","2.5 hr,20"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)

        end

        function testUITableCategorical(testCase)

            T = table( ...
                categorical(["Red";"Blue"]), ...
                [1;2], ...
                'VariableNames',{'Color','Value'});

            fig = uifigure;
            uit = uitable(fig,"Data",T);

            testCase.verifyWarningFree(@() copytable(uit));

            expectedLines = {strjoin(string(uit.ColumnName(:)'),','),...
                "Red,1","Blue,2"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)
        end

        function testUITableMixedTypes(testCase)

            T = table( ...
                ["A";"B"], ...
                [pi;exp(1)], ...
                logical([1;0]), ...
                datetime(2025,1,1)+days([0;1]), ...
                'VariableNames',{'Name','Value','Flag','Time'});

            fig = uifigure;
            uit = uitable(fig,"Data",T);

            testCase.verifyWarningFree(@() copytable(uit));

            expectedLines = {strjoin(string(uit.ColumnName(:)'),','),...
                "A,3.141592653589793,true,01-Jan-2025","B,2.718281828459045,false,02-Jan-2025"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)

        end

        function testUITableCellMixedTypes(testCase)
            data = {'John', 25, true
                'Sarah', 30, false};
            fig = uifigure;
            uit = uitable(fig, ...
                "Data",data, ...
                "ColumnName",{'Name','Age','Flag'});
            testCase.verifyWarningFree(@() copytable(uit));
            
            expectedLines = {strjoin(string(uit.ColumnName(:)'),','),...
                "John,25,true","Sarah,30,false"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)
        end

        function testUITableCharData(testCase)
            data = {'John', 25
                'Sarah', 30};
            fig = uifigure;
            uit = uitable(fig, ...
                "Data",data, ...
                "ColumnName",{'Name','Age'});
            testCase.verifyWarningFree(@() copytable(uit));
            
            expectedLines = {strjoin(string(uit.ColumnName(:)'),','),...
                "John,25","Sarah,30"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)
        end

        function testUITableEmptyStrings(testCase)
            data = {'John', 25
                '',30};
            fig = uifigure;
            uit = uitable(fig, ...
                "Data",data, ...
                "ColumnName",{'Name','Age'});
            testCase.verifyWarningFree(@() copytable(uit));
            
            expectedLines = {strjoin(string(uit.ColumnName(:)'),','),...
                "John,25",",30"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)
        end

        function testUITableCommaInString(testCase)
            data = {'Smith, John', 25
                'Brown, Sarah', 30};
            fig = uifigure;
            uit = uitable(fig, ...
                "Data",data, ...
                "ColumnName",{'Name','Age'});
            testCase.verifyWarningFree(@() copytable(uit));
            
            expectedLines = {strjoin(string(uit.ColumnName(:)'),','),...
                """Smith, John"",25","""Brown, Sarah"",30"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)
        end

        function testUITableQuotesInString(testCase)
            data = {'He said "Hello"', 25
                'She said "Bye"', 30};
            fig = uifigure;
            uit = uitable(fig, ...
                "Data",data, ...
                "ColumnName",{'Name','Age'});
            testCase.verifyWarningFree(@() copytable(uit));
            
            expectedLines = {strjoin(string(uit.ColumnName(:)'),','),...
                """He said """"Hello"""""",25","""She said """"Bye"""""",30"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)
        end

        function testUITableDoublePrecision(testCase)
            x = pi;
            fig = uifigure;
            uit = uitable(fig, ...
                "Data",{x}, ...
                "ColumnName",{'Value'});
            copytable(uit);
            
            expectedLines = {strjoin(string(uit.ColumnName(:)'),','),...
                "3.141592653589793"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 

            delete(fig)
        end

    end
end