% This test file was generated by Copilot. Validate generated output before use.
classdef TcopytableTestTimetable < matlab.unittest.TestCase
    methods(Test)
        function testBaseTimetable(testCase)
            MeasurementTime = datetime(["2015-12-18 08:03:05";"2015-12-18 10:03:17";"2015-12-18 12:03:13"]);
            Temp = [37.3;39.1;42.3];
            Pressure = [30.1;30.03;29.9];
            WindSpeed = [13.4;6.5;7.3];
            TT = timetable(MeasurementTime,Temp,Pressure,WindSpeed);

            testCase.verifyWarningFree(@() copytable(TT));
        end

        function testEmptyTimetable(testCase)
            TT = timetable(); % empty timetable
            testCase.verifyError(@() copytable(TT),'MATLAB:validators:mustBeNonempty');
        end

        function testSingleRowTimetable(testCase)
            MeasurementTime = datetime("2020-01-01 00:00:00");
            A = 1;
            TT = timetable(MeasurementTime,A);
            testCase.verifyWarningFree(@() copytable(TT));
        end

        function testDifferentVarTypes(testCase)
            MeasurementTime = datetime(["2021-06-01 08:00:00"; "2021-06-01 09:00:00"]);
            Num = [1;2];
            Char = ["a"; "b"];
            Cat = categorical(["low"; "high"]);
            TT = timetable(MeasurementTime, Num, Char, Cat);
            testCase.verifyWarningFree(@() copytable(TT));
        end

        function testRowTimesDuplicate(testCase)
            MeasurementTime = datetime(["2022-03-03 10:00:00"; "2022-03-03 10:00:00"]);
            X = [10; 20];
            TT = timetable(MeasurementTime, X);
            testCase.verifyWarningFree(@() copytable(TT));
        end

        function testLargeTimetable(testCase)
            n = 1000;
            MeasurementTime = datetime(2020,1,1) + minutes(0:n-1);
            Data = rand(n,3);
            TT = timetable(MeasurementTime', Data(:,1), Data(:,2), Data(:,3));
            testCase.verifyWarningFree(@() copytable(TT));
        end

        function testInvalidInputType(testCase)
            % copytable should accept only timetables; verify that non-timetable
            % input throws an error
            A = rand(5);
            testCase.verifyError(@() copytable(A), 'MATLAB:validators:mustBeA'); 
        end
    end
end