% This is an autogenerated sample test
classdef TcopytableDifferentDelimiters < matlab.unittest.TestCase
    methods (Test)
        function testBaseTabDelimiter(testCase)
            % Specify the inputs
            LastName = ["Sanchez";"Johnson"];
            Age = {38;[]};
            yy = {single(4);half(3)};
            T = table(LastName, Age, yy);
            delimiter = '\t';
            copytable(T,delimiter)

            actual = clipboard('paste');
            actualDouble = double(actual);
            expectedLines = [76, 97, 115, 116, 78, 97, 109, 101, 9, 65, 103,...
                101, 9, 121, 121, 10, 83, 97, 110, 99, 104, 101, 122, 9, 51,...
                56, 9, 52, 10, 74, 111, 104, 110, 115, 111, 110, 9, 9, 51];

            testCase.verifyEqual(actualDouble, expectedLines);
        end

        function testBaseCarriageDelimiter(testCase)
            % Specify the inputs
            LastName = ["Sanchez";"Johnson"];
            Age = {38;[]};
            yy = {single(4);half(3)};
            T = table(LastName, Age, yy);
            delimiter = '\r';
            copytable(T,delimiter)

            actual = clipboard('paste');
            expected = ['LastName',char(13),'Age',char(13),'yy',newline,...
                'Sanchez',char(13),'38',char(13),'4',newline,'Johnson',char(13),char(13),'3'];

            testCase.verifyEqual(actual, expected);
        end

        function testBaseNewlineDelimiter(testCase)
            % Specify the inputs
            LastName = ["Sanchez";"Johnson"];
            Age = {38;[]};
            yy = {single(4);half(3)};
            T = table(LastName, Age, yy);
            delimiter = '\n';
            copytable(T,delimiter)

            actual = clipboard('paste');
            expectedLines = ['LastName',newline,'Age',newline,'yy',newline,...
                'Sanchez',newline,'38',newline,'4',newline,'Johnson',...
                newline,'',newline,'3'];
            
            testCase.verifyEqual(actual, expectedLines);
        end

        function testTwoDelimiters(testCase)
            Data = [-10-3i; 3+4i; 30];
            rowTimes = (calmonths(1:3))';
            T = table(rowTimes, Data);
            delimiter = [",";";"];
            testCase.verifyError(@() copytable(T,delimiter),'MATLAB:validators:mustBeTextScalar')
        end
    end
end