% This test file was generated by Copilot. Validate generated output before use.
classdef TcopytableTestTable < matlab.unittest.TestCase
    methods(Test)
        function testBasePerformance(testCase)
            n = 1e5;
            data = string(rand(n,1));
            T = table(data);

            actualTiming = timeit(@() copytable(T));
            allowableTiming = 0.25; %seconds

            testCase.verifyLessThanOrEqual(actualTiming,allowableTiming)
        end

        function testCopySimpleTable(testCase)
            LastName = ["Sanchez";"Johnson"];
            Age = [38;43];
            T = table(LastName, Age);

            copytable(T)
            actual = clipboard('paste');
            actualDouble = double(actual);
            expectedDouble = [76, 97, 115, 116, 78, 97, 109, 101, 44, 65, 103,...
                101, 10, 83, 97, 110, 99, 104, 101, 122, 44, 51, 56, 10, 74,...
                111, 104, 110, 115, 111, 110, 44, 52, 51];

            testCase.verifyEqual(actualDouble, expectedDouble);
        end

        function testCopyTableWithNonScalarColumnThrows(testCase)
            LastName = ["Sanchez";"Johnson"];
            BloodPressure = [124 93; 109 77]; % 2x2 non-scalar per row
            T = table(LastName, BloodPressure);

            testCase.verifyError(@() copytable(T), 'copytable:InvalidTableSize');
        end

        function testCopyTableWithCharTableVars(testCase)
            Names = ['John '; 'Mary '];
            T = table(Names);
            copytable(T)

            actual = clipboard('paste');
            actualDouble = double(actual);
            expectedDouble = [78, 97, 109, 101, 115, 10, 74, 111, 104, 110,...
                32, 10, 77, 97, 114, 121, 32];

            testCase.verifyEqual(actualDouble,expectedDouble)
        end

        function testCopyTableWithMatrixAsInput(testCase)
            BloodPressure = [124 93; 109 77];

            testCase.verifyError(@() copytable(BloodPressure), 'MATLAB:validators:mustBeA');
        end

        function testCopyTableWithStrings(testCase)
            Names = ["A"; "B"; "C"];
            Value = [1;2;3];
            T = table(Names, Value);

            testCase.verifyWarningFree(@() copytable(T));

            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "A,1", "B,2", "C,3"};
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines);
        end

        function testMixedDataTypes(testCase)
            Names = ["A"; "B"];
            Value = [1; 2];
            Flag = logical([1; 0]);
            T = table(Names, Value, Flag);

            testCase.verifyWarningFree(@() copytable(T));

            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "A,1,true", "B,2,false"};
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines);
        end

        function testCellstrAndNumeric(testCase)
            Names = {'John'; 'Sarah'};
            Age = [25; 30];
            T = table(Names, Age);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "John,25", "Sarah,30"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines);
        end

        function testEmptyTable(testCase)
            T = table(string.empty(0,1), zeros(0,1), ...
                'VariableNames', {'Name','Value'});

            testCase.verifyError(@() copytable(T), 'MATLAB:validators:mustBeNonempty');
            
        end

        function testBaseEmptyTable(testCase)
            T = table;
            testCase.verifyError(@() copytable(T), 'MATLAB:validators:mustBeNonempty');
        end

        function testSingleRow(testCase)
            T = table("OnlyOne", 42);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "OnlyOne,42"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines);
        end

        function testColumnVectorIsAllowed(testCase)
            A = (1:3)';          % 3x1 (valid)
            B = (4:6)';
            T = table(A, B);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "1,4", "2,5", "3,6"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines);
        end

        function testNonScalarColumnIndex(testCase)
            A = [1;2];
            B = [3 4; 5 6]; 
            T = table(A, B);

            testCase.verifyError(@() copytable(T), 'copytable:InvalidTableSize');
        end


        function testFullPrecisionDouble(testCase)
            x = pi;
            T = table(x);

            copytable(T);
            result = clipboard('paste');

            doesResultContainFullPrecisionPi = contains(result,'3.14159265358979');
            testCase.verifyTrue(doesResultContainFullPrecisionPi)
        end

        function testMixedNumericTypes(testCase)

            T = table( ...
                int8([1;2]), ...
                uint32([3;4]), ...
                single([pi;exp(1)]), ...
                [sqrt(2);sqrt(3)], ...
                'VariableNames',{'I8','U32','Single','Double'});

            testCase.verifyWarningFree(@() copytable(T));


            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "1,3,3.1415927,1.414213562373095", "2,4,2.7182817,1.732050807568877"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines);
        end

        function testDatetime(testCase)

            Time = datetime(2025,1,1) + days([0;1;2]);
            Value = [1;2;3];

            T = table(Time,Value);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "01-Jan-2025,1", "02-Jan-2025,2", "03-Jan-2025,3"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines);
        end

        function testDatetimeWithMissing(testCase)

            Time = [datetime(2025,1,1); NaT];
            Value = [1;2];

            T = table(Time,Value);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "01-Jan-2025,1", ",2"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines);
        end

        function testDuration(testCase)

            Elapsed = hours([1.5;2.5;3.5]);
            Value = [10;20;30];

            T = table(Elapsed,Value);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "1.5 hr,10", "2.5 hr,20", "3.5 hr,30"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines);
            
        end

        function testStringWithMissing(testCase)

            Names = ["John"; missing];
            Value = [1;2];

            T = table(Names,Value);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "John,1", ",2"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines);            
        end

        function testCharCellColumn(testCase)

            Names = {'John';'Sarah';'Bob'};
            Value = [1;2;3];

            T = table(Names,Value);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "John,1", "Sarah,2", "Bob,3"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines);   
        end

        function testCategorical(testCase)

            Color = categorical(["Red";"Green";"Blue"]);
            Value = [10;20;30];

            T = table(Color,Value);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "Red,10", "Green,20", "Blue,30"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines);   
        end

        function testLogical(testCase)

            Flag = [true;false;true];
            Value = [1;2;3];

            T = table(Flag,Value);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "true,1", "false,2", "true,3"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines);   
        end

        function testEmptyStrings(testCase)

            Names = ["A";"";"C"];
            Values = [1;2;3];

            T = table(Names,Values);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "A,1", ",2", "C,3"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 
        end

        function testStringContainingComma(testCase)

            Name = ["Smith, John";"Jones, Sarah"];
            Value = [1;2];

            T = table(Name,Value);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                """Smith, John"",1", """Jones, Sarah"",2"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 
        end

        function testCellVariableMixedTypes(testCase)

            Mixed = {42; "abc"; datetime(2025,1,1)};
            Value = [1;2;3];

            T = table(Mixed,Value);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "42,1", "abc,2","01-Jan-2025,3"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 
        end

        function testCellContainsVectorThrows(testCase)

            Mixed = {[1 2]; [3 4]};
            Value = [1;2];

            T = table(Mixed,Value);

            testCase.verifyError(@() copytable(T), ...
                'copytable:InvalidTableSize');

        end

        function testCellContainsMatricesThrows(testCase)

            Bad = {[1 2;3 4]; [5 6;7 8]};
            T = table(Bad);

            testCase.verifyError(@() copytable(T), ...
                'copytable:InvalidTableSize');

        end

        function testColumnVectorWithMissing(testCase)
            A = (1:3)';          % 3x1 (valid)
            B = (4:6)';
            B(2) = missing;
            T = table(A, B);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "1,4", "2,NaN","3,6"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 
        end

        function testColumnVectorWithNaN(testCase)
            A = (1:3)';          % 3x1 (valid)
            B = (4:6)';
            A(2) = nan;
            T = table(A, B);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "1,4", "NaN,5","3,6"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 
        end

        function testComplexNumbers(testCase)
            T = table(double([1; 3-4i]),single([1-2i; 3+4i]),int8([1; 3-4i]),...
                'VariableNames',{'DoubleComplexValue','SingleComplexValue','Int8ComplexValue'});
            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "1,1-2i,1","3-4i,3+4i,3-4i"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 
        end

        function testTableCalendarDuration(testCase)
            % Create a numeric data variable
            Data = [10; 20; 30];
            rowTimes = (calmonths(1:3))';
            T = table(rowTimes, Data);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "1mo,10","2mo,20","3mo,30"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 
        end

        function testTableUndefinedCategorical(testCase)
            % Create a numeric data variable
            A = categorical([4 1; 2 3; 2 1; 3 4; 1 1],1:3,["red" "green" "blue"]);
            T = table(A(:,1),A(:,2));

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                ",red","green,blue","green,red","blue,","red,red"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 
        end

        function testTableUndefinedCellCategorical(testCase)
            % Create a numeric data variable
            Data = {10; categorical(4,1:3,["red" "green" "blue"]);...
                categorical(3,1:3,["red" "green" "blue"]);30};
            rowTimes = (calmonths(1:4))';
            T = table(rowTimes, Data);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "1mo,10","2mo,","3mo,blue","4mo,30"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 
        end

        function testTableLayeredCells(testCase)
            % Create a numeric data variable
            Data = {{10}; {[]}; {30}};
            rowTimes = (calmonths(1:3))';
            T = table(rowTimes, Data);

            testCase.verifyError(@() copytable(T),'copytable:InvalidTableStructure');
        end

        function testTableMissingCells(testCase)
            % Create a numeric data variable
            Data = [missing; missing; 2];
            rowTimes = [missing; missing; missing];
            T = table(rowTimes, Data);

            testCase.verifyWarningFree(@() copytable(T));
            actual = clipboard('paste');
            actualDouble = double(actual);

            expectedDouble = [114, 111, 119, 84, 105, 109, 101, 115, 44, 68,...
                97, 116, 97, 10, 44, 78, 97, 78, 10, 44, 78, 97, 78, 10, 44, 50];

            testCase.verifyEqual(actualDouble,expectedDouble)
        end

        function testTableWithCategorical(testCase)
            Data = {10; categorical([4 1; 2 3; 2 1; 3 4; 1 1],1:3,["red" "green" "blue"]); 30};
            rowTimes = (calmonths(1:3))';
            T = table(rowTimes, Data);

            testCase.verifyError(@() copytable(T),'copytable:InvalidTableSize');
        end

        function testTableLayeredCellsVector(testCase)
            % Create a numeric data variable
            Data = {{10}; {1:20}; {30}};
            rowTimes = (calmonths(1:3))';
            T = table(rowTimes, Data);

            testCase.verifyError(@() copytable(T),'copytable:InvalidTableStructure');
        end

        function testTableMultiLayeredCells(testCase)
            % Create a numeric data variable
            Data = {{10}; {{20}}; {30}};
            rowTimes = (calmonths(1:3))';
            T = table(rowTimes, Data);

            testCase.verifyError(@() copytable(T),'copytable:InvalidTableStructure');
        end

        function testTableMultiLayeredCellsVector(testCase)
            % Create a numeric data variable
            Data = {{10}; {1,2}; {30}};
            rowTimes = (calmonths(1:3))';
            T = table(rowTimes, Data);

            testCase.verifyError(@() copytable(T),'copytable:InvalidTableStructure');
        end

        function testTableStruct(testCase)

            field = 'f';
            value = {'some text';
                [10, 20, 30];
                magic(5)};
            structVar = struct(field,value);

            Data = [10; 20; 30];
            rowTimes = (calmonths(1:3))';

            T = table(rowTimes, Data,structVar);

            testCase.verifyError(@() copytable(T),'copytable:InvalidTableInput');
        end
        
        function testTableWithFunctionHandle(testCase)
            LastName = ["Sanchez";"Johnson"];
            Age = [38;43];
            Funs = {@sin;@(x,y)cos(x^y)};
            T = table(LastName, Age, Funs);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "Sanchez,38,sin","Johnson,43,""@(x,y)cos(x^y)"""};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 
        end

        function testTableWithDictionary(testCase)
            LastName = ["Sanchez";"Johnson"];
            Age = [38;43];
            names = ["Unicycle" "Bicycle" "Tricycle"];
            wheels = [1 2 3];
            d = dictionary(names,wheels);
            Dictionaries = {d;d};
            T = table(LastName, Age, Dictionaries);

            testCase.verifyError(@() copytable(T),'copytable:InvalidTableSize');
        end

        function testTableWithObjects(testCase)
            LastName = ["Sanchez";"Johnson"];
            Age = [38;43];            
            h = histogram(randn(1000,1));
            handleObj = [h;h.Parent];
            T = table(LastName, Age, handleObj);

            testCase.verifyError(@() copytable(T),'copytable:InvalidTableInput');
            delete(ancestor(h,'figure'))
        end

        function testTableWithObjectsInCell(testCase)
            LastName = ["Sanchez";"Johnson"];
            Age = [38;43];            
            h = histogram(randn(1000,1));
            s.a = 1;
            s.b = {'A','B','C'};
            handleObj = {h;s};
            T = table(LastName, Age, handleObj);

            testCase.verifyError(@() copytable(T),'copytable:InvalidTableSize');
            delete(ancestor(h,'figure'))
        end

        function testTableEmpty(testCase)
            LastName = ["Sanchez";"Johnson"];
            Age = {38;[]};
            yy = {single(4);half(3)};
            T = table(LastName, Age, yy);

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "Sanchez,38,4","Johnson,,3"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 
        end

        function testTableAllTypes(testCase)
            T = table( ...
                [pi; exp(1); pi*1000], ...                                   % double
                single([pi; exp(1); pi*1000]), ...                           % single
                half([pi; exp(1); pi*1000]), ...                             % half
                int32([42; -7; 29]), ...                               % integer
                uint64([2^40; 2^41; 2]), ...                          % unsigned integer
                half([1+2i; 3+4i; 5-6i]), ...                                  % complex half
                ["Hello"; "World"; "Again"], ...                            % string
                ['A'; 'B'; 'C'], ...                                    % char
                datetime(2025,1,1) + days([0;1;2]), ...             % datetime
                duration([1;2;3],[30;45;55],[0;0;0]), ...                % duration
                calmonths([1;2;3]), ...                             % calendar duration
                logical([1;0;1]), ...                               % logical
                {42; "test"; @sin}, ...                             % cell
                'VariableNames', { ...
                'DoubleValue', ...
                'SingleValue', ...
                'HalfValue', ...
                'Int32Value', ...
                'UInt64Value', ...
                'ComplexValue', ...
                'StringValue', ...
                'CharValue', ...
                'DateTimeValue', ...
                'DurationValue', ...
                'CalendarDurationValue', ...
                'LogicalValue', ...
                'CellValue'});

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = {strjoin(string(T.Properties.VariableNames),','),...
                "3.141592653589793,3.1415927,3.1406,42,1099511627776,1+2i,Hello,A,01-Jan-2025,01:30:00,1mo,true,42",...
                "2.718281828459045,2.7182817,2.7188,-7,2199023255552,3+4i,World,B,02-Jan-2025,02:45:00,2mo,false,test",...
                "3141.592653589793,3141.5928,3142,29,2,5-6i,Again,C,03-Jan-2025,03:55:00,3mo,true,sin"};
            actual = clipboard('paste');
            actual = strrep(actual, sprintf('\r\n'), newline);
            lines = strsplit(strtrim(actual), '\n');
            lines = cellfun(@strtrim, lines, 'UniformOutput', false);
            lines = cellfun(@string,  lines, 'UniformOutput', false);

            testCase.verifyEqual(lines, expectedLines); 
        end

        function testTableAllTypesCell(testCase)

            T = table( ...
                {pi;...                                   % double
                single(pi);...                           % single
                half(pi);...                             % half
                int32(42); ...                               % integer
                uint64(2+3i); ...                          % unsigned integer
                half(-1-2i); ...                                  % complex half
                string(missing); ...                            % string
                'A'; ...                                    % char
                datetime(2025,1,1); ...             % datetime
                duration(1,30,0); ...                % duration
                calmonths(1); ...                             % calendar duration
                true; ...                               % logical
                @(x,y)sin(x^y)}, ...                             % cell,...
                'VariableNames', "sometable");

            testCase.verifyWarningFree(@() copytable(T));

            expectedLines = [115, 111, 109, 101, 116, 97, 98, 108, 101, 10, 51,...
                46, 49, 52, 49, 53, 57, 50, 54, 53, 51, 53, 56, 57, 55, 57, 51,...
                10, 51, 46, 49, 52, 49, 53, 57, 50, 55, 10, 51, 46, 49, 52, 48,...
                54, 50, 53, 10, 52, 50, 10, 50, 43, 51, 105, 10, 45, 49, 45, 50,...
                105, 10, 10, 65, 10, 48, 49, 45, 74, 97, 110, 45, 50, 48, 50,...
                53, 10, 48, 49, 58, 51, 48, 58, 48, 48, 10, 49, 109, 111, 10,...
                116, 114, 117, 101, 10, 34, 64, 40, 120, 44, 121, 41, 115, 105,...
                110, 40, 120, 94, 121, 41, 34];
            actual = clipboard('paste');
            actualDouble = double(actual);

            testCase.verifyEqual(expectedLines, actualDouble);
        end

    end
end